language: r
cache: packages

before_install:
  - Rscript -e 'install.packages("cwbtools")'

r_packages:
  - cwbtools
  - RCurl
  - curl
  - polmineR
  - SnowballC
  - covr
  - rmarkdown

r_github_packages:
  - r-lib/covr

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all", token = "36cf23e7-4231-4329-b680-f052fece17dc")'
